/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LockedRouteImport } from './routes/locked'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SessionExpiredRouteImport } from './routes/session-expired'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppAboutRouteImport } from './routes/_app.about'
import { Route as AppAccountRouteImport } from './routes/_app.account'
import { Route as AppDocsRouteImport } from './routes/_app.docs'
import { Route as AppExplorerRouteImport } from './routes/_app.explorer'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppRolesRouteImport } from './routes/_app.roles'
import { Route as AppStorageRouteImport } from './routes/_app.storage'
import { Route as AppTerminalRouteImport } from './routes/_app.terminal'
import { Route as AppTrashRouteImport } from './routes/_app.trash'
import { Route as AppUploadsRouteImport } from './routes/_app.uploads'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as ApiLocalRouteImport } from './routes/api.local'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LockedRoute = LockedRouteImport.update({
  id: '/locked',
  path: '/locked',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionExpiredRoute = SessionExpiredRouteImport.update({
  id: '/session-expired',
  path: '/session-expired',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppDocsRoute = AppDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AppRoute,
} as any)
const AppExplorerRoute = AppExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppStorageRoute = AppStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => AppRoute,
} as any)
const AppTerminalRoute = AppTerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => AppRoute,
} as any)
const AppTrashRoute = AppTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AppRoute,
} as any)
const AppUploadsRoute = AppUploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const ApiLocalRoute = ApiLocalRouteImport.update({
  id: '/api/local',
  path: '/api/local',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/locked': typeof LockedRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/session-expired': typeof SessionExpiredRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof AppAboutRoute
  '/account': typeof AppAccountRoute
  '/docs': typeof AppDocsRoute
  '/explorer': typeof AppExplorerRoute
  '/notifications': typeof AppNotificationsRoute
  '/roles': typeof AppRolesRoute
  '/storage': typeof AppStorageRoute
  '/terminal': typeof AppTerminalRoute
  '/trash': typeof AppTrashRoute
  '/uploads': typeof AppUploadsRoute
  '/users': typeof AppUsersRoute
  '/api/local': typeof ApiLocalRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/locked': typeof LockedRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/session-expired': typeof SessionExpiredRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof AppAboutRoute
  '/account': typeof AppAccountRoute
  '/docs': typeof AppDocsRoute
  '/explorer': typeof AppExplorerRoute
  '/notifications': typeof AppNotificationsRoute
  '/roles': typeof AppRolesRoute
  '/storage': typeof AppStorageRoute
  '/terminal': typeof AppTerminalRoute
  '/trash': typeof AppTrashRoute
  '/uploads': typeof AppUploadsRoute
  '/users': typeof AppUsersRoute
  '/api/local': typeof ApiLocalRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/locked': typeof LockedRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/session-expired': typeof SessionExpiredRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/about': typeof AppAboutRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/docs': typeof AppDocsRoute
  '/_app/explorer': typeof AppExplorerRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/roles': typeof AppRolesRoute
  '/_app/storage': typeof AppStorageRoute
  '/_app/terminal': typeof AppTerminalRoute
  '/_app/trash': typeof AppTrashRoute
  '/_app/uploads': typeof AppUploadsRoute
  '/_app/users': typeof AppUsersRoute
  '/api/local': typeof ApiLocalRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/locked'
    | '/login'
    | '/reset-password'
    | '/session-expired'
    | '/setup'
    | '/sitemap.xml'
    | '/about'
    | '/account'
    | '/docs'
    | '/explorer'
    | '/notifications'
    | '/roles'
    | '/storage'
    | '/terminal'
    | '/trash'
    | '/uploads'
    | '/users'
    | '/api/local'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/locked'
    | '/login'
    | '/reset-password'
    | '/session-expired'
    | '/setup'
    | '/sitemap.xml'
    | '/about'
    | '/account'
    | '/docs'
    | '/explorer'
    | '/notifications'
    | '/roles'
    | '/storage'
    | '/terminal'
    | '/trash'
    | '/uploads'
    | '/users'
    | '/api/local'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/forgot-password'
    | '/locked'
    | '/login'
    | '/reset-password'
    | '/session-expired'
    | '/setup'
    | '/sitemap.xml'
    | '/_app/about'
    | '/_app/account'
    | '/_app/docs'
    | '/_app/explorer'
    | '/_app/notifications'
    | '/_app/roles'
    | '/_app/storage'
    | '/_app/terminal'
    | '/_app/trash'
    | '/_app/uploads'
    | '/_app/users'
    | '/api/local'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LockedRoute: typeof LockedRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SessionExpiredRoute: typeof SessionExpiredRoute
  SetupRoute: typeof SetupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiLocalRoute: typeof ApiLocalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locked': {
      id: '/locked'
      path: '/locked'
      fullPath: '/locked'
      preLoaderRoute: typeof LockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session-expired': {
      id: '/session-expired'
      path: '/session-expired'
      fullPath: '/session-expired'
      preLoaderRoute: typeof SessionExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/docs': {
      id: '/_app/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof AppDocsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explorer': {
      id: '/_app/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof AppExplorerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles': {
      id: '/_app/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/storage': {
      id: '/_app/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof AppStorageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/terminal': {
      id: '/_app/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof AppTerminalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trash': {
      id: '/_app/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof AppTrashRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/uploads': {
      id: '/_app/uploads'
      path: '/uploads'
      fullPath: '/uploads'
      preLoaderRoute: typeof AppUploadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/local': {
      id: '/api/local'
      path: '/api/local'
      fullPath: '/api/local'
      preLoaderRoute: typeof ApiLocalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppAccountRoute: typeof AppAccountRoute
  AppDocsRoute: typeof AppDocsRoute
  AppExplorerRoute: typeof AppExplorerRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppRolesRoute: typeof AppRolesRoute
  AppStorageRoute: typeof AppStorageRoute
  AppTerminalRoute: typeof AppTerminalRoute
  AppTrashRoute: typeof AppTrashRoute
  AppUploadsRoute: typeof AppUploadsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppAccountRoute: AppAccountRoute,
  AppDocsRoute: AppDocsRoute,
  AppExplorerRoute: AppExplorerRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppRolesRoute: AppRolesRoute,
  AppStorageRoute: AppStorageRoute,
  AppTerminalRoute: AppTerminalRoute,
  AppTrashRoute: AppTrashRoute,
  AppUploadsRoute: AppUploadsRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LockedRoute: LockedRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SessionExpiredRoute: SessionExpiredRoute,
  SetupRoute: SetupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiLocalRoute: ApiLocalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
